---
background_runner: Multithread

multithread:
  priority_threshold: 50
  pool_size: 20
  max_threads: 100
  priority:
    CommentNotificationMailer: 80
    DeployFixMarker: 70
    DeployNotificationMailer: 80
    JiraStatusWorker: 20
    ObfuscationMapWorker: 60
    OccurrenceNotificationMailer: 80
    OccurrencesWorker: 40
    PagerDutyAcknowledger: 20
    PagerDutyNotifier: 80
    PagerDutyResolver: 20
    ProjectRepoFetcher: 30
    SourceMapWorker: 60
    SymbolicationWorker: 60

resque:
  development: "localhost:6379"
  production: "localhost:6379"
  test: "localhost:6379"
  pool:
    squash: 2
  queue:
    CommentNotificationMailer: squash
    DeployFixMarker: squash
    DeployNotificationMailer: squash
    JiraStatusWorker: squash
    ObfuscationMapWorker: squash
    OccurrenceNotificationMailer: squash
    OccurrencesWorker: squash
    PagerDutyAcknowledger: squash
    PagerDutyNotifier: squash
    PagerDutyResolver: squash
    ProjectRepoFetcher: squash
    SourceMapWorker: squash
    SymbolicationWorker: squash

sidekiq:
  redis:
    url: "redis://localhost:6379"
    namespace: squash
    pidfile: ./tmp/pids/sidekiq.pid
    concurrency: 12
    queues:
    - [emails, 3]
    - [git, 2]
    - [occurrences, 1]
    - [processing, 3]
    - [services, 2]
  worker_options:
    CommentNotificationMailer:
      queue: emails
    DeployFixMarker:
      queue: processing
    DeployNotificationMailer:
      queue: emails
    JiraStatusWorker:
      queue: services
      retry: false
    ObfuscationMapWorker:
      queue: processing
    OccurrenceNotificationMailer:
      queue: emails
    OccurrencesWorker:
      queue: occurrences
      retry: false
    PagerDutyAcknowledger:
      queue: services
    PagerDutyNotifier:
      queue: services
    PagerDutyResolver:
      queue: services
    ProjectRepoFetcher:
      queue: git
    SourceMapWorker:
      queue: processing
    SymbolicationWorker:
      queue: processing
